### ISSUE TITLE
Se debe poder recuperar una lista ordenada con las claves almacenadas en la lista.

### ISSUE THREAD

**Issue by evolentini** [vacagonzalo/UBA-Testing-TP2#1]
En la implementación actual se recupera una lista de las parejas, y el requerimiento es que solo se devuelva una lista de las claves.

**Comment by vacagonzalo** [comment]
> En la implementación actual se recupera una lista de las parejas, y el requerimiento es que solo se devuelva una lista de las claves.

Ops! corregido
