### ISSUE TITLE
Tenes aprobado el TP2 con correcciones

### ISSUE THREAD

**Issue by evolentini** [vacagonzalo/UBA-Testing-TP2#2]
Tenes solo una corrección menor para hacer, tu nota actual es 2/3 (algo como un 8/10) pero si haces la corrección pasarías a tener 3/3.

**Comment by vacagonzalo** [comment]
Muchas gracias! ya hice la corrección!!!

**Comment by evolentini** [comment]
Listo, ya aumente la nota en función de las correcciones. Ahora tenes 3/3

**Comment by vacagonzalo** [comment]
¡Hola Esteban! ¡¡¡barbaro mil gracias!!!
    Está el TP3 para corregir también, acá está el link
<https://github.com/vacagonzalo/Testing-TP3> por las dudas.
Muchas gracias y saludos,
Gonzalo
